#!/bin/bash

source activate bdas
cd ../..
host_name="6"
for d in ${!host_name}; do
  nohup python -m benchmarks.ea_time -s DAG -t 36000 -d $d >$d.txt 2>&1 &
done

#logs_dir="ea_dag_10h_logs"
#if [ ! -d "$logs_dir" ]; then
#  mkdir $logs_dir
#fi
#
#mv [[:digit:]]*.txt $logs_dir
